# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-strongdm
  description: This component provisions strongDM gateway, relay and roles
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component









